### ISSUE TITLE
Seems to be broken with ElasticPress 2.4

### ISSUE THREAD

**Issue by robertminer1** [thinkshout/ep-geo#4]
Hi!  This plugin is great!  It seems to have broken with the latest update of ElasticPress though.

**Comment by wxactly** [comment]
@robertminer1 - Do you have any more detail about what seems to be broken? I tried upgrading a site to ElasticPress 2.4, but I can't get that new version to return field data on posts at all... Is it just an issue with version 2.4 itself?

**Comment by robertminer1** [comment]
@wxactly Those are some good questions, I should probably look into that.  Elastic Press still seems to work for me, but let me do some digging around and let you know.

**Comment by robertminer1** [comment]
https://github.com/10up/ElasticPress/issues/963

Seems like this may be the problem.

**Comment by wxactly** [comment]
@robertminer1 This is fixed on the geo_shape branch https://github.com/thinkshout/ep-geo/pull/6

Wanted to ping ya in case you wanted to give it a try before I merge it in. FYI, you'll need to reindex elasticsearch

**Comment by wxactly** [comment]
Merged into master
