### ISSUE TITLE
Get distance value for each post

### ISSUE THREAD

**Issue by ciarlystreet** [thinkshout/ep-geo#5]
Hi, this plugin is amazing! It's possible know the distance value for each post obtained from geo query?

**Comment by wxactly** [comment]
Hi @ciarlystreet! If you sort by distance, elasticsearch returns the actual distance value as the sort value on each result. Then you can use an elasticpress hook to pull that into your post object, something like:

```php
add_filter( 'ep_retrieve_the_post', function ( $post, $hit ) {
	$post['geo_distance'] = $hit['sort'][0];
	return $post;
}, 10, 2 );
```

**Comment by wxactly** [comment]
Wanted to leave a quick follow-up here... you actually need to implement the hook mentioned above, PLUS an additional hook to allow elasticpress to set this value on your post object:
```php
add_filter( 'ep_search_post_return_args', function ( $post_return_args ) {
	$post_return_args[] = 'geo_distance';

	return $post_return_args;
} );
```

Then you will be able to access this property on your post object in the loop:
```php
global $post;

echo $post->geo_distance;
```
