### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by tunguyenatwork** [thinkshout/ep-geo#8]
Thanks for the module.  It works really well.  Is that possible to call the module as restAPI and provide the parameters (long, lat, and distance) to receive a result as of a list matched posts?

**Comment by wxactly** [comment]
Hi @tunguyenatwork - this plugin does not provide direct support for REST API. However, ElasticPress integrates with WP_Query, so you should be able to write some integration code that would enable you to filter a REST API endpoint by long, lat, and distance.

Here's a link to some examples showing different ways to do this: https://wordpress.stackexchange.com/q/271877/108463

Just take care that you also set `'ep_integrate' => true` on your WP_Query as well (see http://10up.github.io/ElasticPress/tutorial-indexables.html)

**Comment by tunguyenatwork** [comment]
Thanks for the advice. I will give it a try
